spring.application.name=my-todo-list

driver_class_name=${DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
db_user=${DB_USER}
dbpassword=${DB_PASSWORD}
db_url=${DB_URL}

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=INFO
